### ISSUE TITLE
Our Services page - Sidebar Services lists: Are we supposed to link the Services list to its respective Services post on the listing page instead of its single page?

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/The-Moving-Man#38]
![image](https://cloud.githubusercontent.com/assets/11186304/6860418/f4512e64-d462-11e4-88fc-6f0a1d620df8.png)

**Comment by genesiscebudigital** [comment]
Yes Because There is pagination . ,

**Comment by maluzynel** [comment]
Please ask for confirmation for way of implementation regarding this. I guess, the sidebar services links should anchor to the posts on the same page in Our Services page.
