### ISSUE TITLE
Testimonials page: 'Load more Testimonials' on the bottom portion in the page seems not working in iTouch 4 mobile device.

### ISSUE THREAD

**Issue by maluzynel** [titan-cebu/The-Moving-Man#55]
iTouch 4

![image](https://cloud.githubusercontent.com/assets/11186304/6861332/8ef866c4-d46f-11e4-86ea-f3434ea253e4.png)

**Comment by genesiscebudigital** [comment]
I will add load more button . , I can't Check here

**Comment by maluzynel** [comment]
Load more button should be remove as this was not specified on the design specs.
